version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: ["npm", "run", "start"]
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # To handle file changes in development
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/relay-server
    command: ["node", "index.js"]
    ports:
      - "8081:8081"
    volumes:
      - ./relay-server:/app/relay-server
    environment:
      - NODE_ENV=production
      - PORT=8081
      - OPENAI_API_KEY=${OPENAI_API_KEY} # Pass API key from the environment
